import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { roboto } from "@/font/font";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${roboto.className} h-full antialiased`} suppressHydrationWarning>
      <body className="min-h-full flex flex-col bg-color-background text-color-foreground">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
